//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributorLanguage
    {
        public int Id { get; set; }
        public int ContributorId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> FluencyId { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        public virtual Fluency Fluency { get; set; }
        public virtual Language Language { get; set; }
    }
}
