//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DictionaryEntities : DbContext
    {
        public DictionaryEntities()
            : base("name=DictionaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContributorImage> ContributorImages { get; set; }
        public virtual DbSet<ContributorLanguage> ContributorLanguages { get; set; }
        public virtual DbSet<Contributor> Contributors { get; set; }
        public virtual DbSet<EthnicGroup> EthnicGroups { get; set; }
        public virtual DbSet<Fluency> Fluencies { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LexemeEntry> LexemeEntries { get; set; }
        public virtual DbSet<LexemeEntryType> LexemeEntryTypes { get; set; }
        public virtual DbSet<Lexeme> Lexemes { get; set; }
        public virtual DbSet<PartsOfSpeech> PartsOfSpeeches { get; set; }
        public virtual DbSet<SenseExample> SenseExamples { get; set; }
        public virtual DbSet<SenseImage> SenseImages { get; set; }
        public virtual DbSet<SenseReference> SenseReferences { get; set; }
        public virtual DbSet<Sens> Senses { get; set; }
        public virtual DbSet<SenseSource> SenseSources { get; set; }
        public virtual DbSet<SenseXReference> SenseXReferences { get; set; }
        public virtual DbSet<Sex> Sexes { get; set; }
        public virtual DbSet<SpeechEventComment> SpeechEventComments { get; set; }
        public virtual DbSet<SpeechEventContributor> SpeechEventContributors { get; set; }
        public virtual DbSet<SpeechEventCreator> SpeechEventCreators { get; set; }
        public virtual DbSet<SpeechEventFile> SpeechEventFiles { get; set; }
        public virtual DbSet<SpeechEventFileType> SpeechEventFileTypes { get; set; }
        public virtual DbSet<SpeechEvent> SpeechEvents { get; set; }
        public virtual DbSet<SpeechEventTopic> SpeechEventTopics { get; set; }
        public virtual DbSet<SpeechEventType> SpeechEventTypes { get; set; }
    }
}
