//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenseXReference
    {
        public int Id { get; set; }
        public int SenseId { get; set; }
        public int Order { get; set; }
        public int XReferenceId { get; set; }
    
        public virtual LexemeEntry LexemeEntry { get; set; }
        public virtual Sens Sens { get; set; }
    }
}
