//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sens()
        {
            this.SenseImages = new HashSet<SenseImage>();
            this.SenseReferences = new HashSet<SenseReference>();
            this.SenseSources = new HashSet<SenseSource>();
            this.SenseXReferences = new HashSet<SenseXReference>();
        }
    
        public int Id { get; set; }
        public int LexemeEntryId { get; set; }
        public int Order { get; set; }
        public string EnglishDefinition { get; set; }
        public string EnglishGloss { get; set; }
        public string EnglishReversal { get; set; }
        public string NationalDefinition { get; set; }
        public string NationalGloss { get; set; }
        public string NationalReversal { get; set; }
        public string UsageComment { get; set; }
        public string ScientificName { get; set; }
        public string EncyclopaedicInfo { get; set; }
    
        public virtual LexemeEntry LexemeEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenseImage> SenseImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenseReference> SenseReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenseSource> SenseSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenseXReference> SenseXReferences { get; set; }
    }
}
