//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SenseReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SenseReference()
        {
            this.SenseExamples = new HashSet<SenseExample>();
        }
    
        public int Id { get; set; }
        public int SenseId { get; set; }
        public int Order { get; set; }
        public string TextReference { get; set; }
        public string EnglishTranslation { get; set; }
        public Nullable<int> ContributorId { get; set; }
    
        public virtual Contributor Contributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SenseExample> SenseExamples { get; set; }
        public virtual Sens Sens { get; set; }
    }
}
