//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechEventTopic
    {
        public int Id { get; set; }
        public int SpeechEventId { get; set; }
        public string Topic { get; set; }
    
        public virtual SpeechEvent SpeechEvent { get; set; }
    }
}
